source "https://rubygems.org"

gem 'bundler'
gem 'require_all'
gem 'sinatra'
gem 'twilio-ruby'
gem 'rack'
gem 'rake'
gem 'rack-flash3'
gem 'rspec'
gem 'rack-test'
gem 'shotgun'
gem 'haml'
gem 'rubocop'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'