default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  # <<: *default
  # DATABASE_URL: postgresql://ubuntu:@127.0.0.1:5432/circle_test
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  database: <%= ENV['DATABASE_NAME'] || 'microlearndb' %>
  username: <%= ENV['DATABASE_USER'] || 'microlearnadmin' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'MicroLearn1' %>

test:
  #<<: *default
  #DATABASE_URL: postgresql://ubuntu:@127.0.0.1:5432/circle_test
  # adapter: postgresql
  # encoding: unicode
  # pool: 5
  # host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  # database: <%= ENV['DATABASE_NAME'] || 'microlearndb' %>
  # username: <%= ENV['DATABASE_USER'] || 'microlearnadmin' %>
  # password: <%= ENV['DATABASE_PASSWORD'] || 'MicroLearn1' %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  database: <%= ENV['DATABASE_NAME'] || 'sinatra' %>
  username: <%= ENV['DATABASE_USER'] || 'sinatra' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'sinatra' %>
  