default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: db/test.sqlite3

production:, development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  database: <%= ENV['DATABASE_NAME'] || 'microlearndb' %>
  username: <%= ENV['DATABASE_USER'] || 'microlearnadmin' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'MicroLearn@1' %>
  